version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3336:3306"
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: artio
      MYSQL_DATABASE: web_atrio
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uroot -e 'SHOW DATABASES LIKE \"web_atrio\";' | grep web_atrio || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web_atrio
      SPRING_DATASOURCE_USERNAME: web
      SPRING_DATASOURCE_PASSWORD: artio
      SPRING_PROFILES_ACTIVE: qa

  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
